<?php
namespace doublesecretagency\notifier\tests\unit;

use doublesecretagency\notifier\models\BaseEnvelope;
use doublesecretagency\notifier\models\OutboundBluesky;
use PHPUnit\Framework\TestCase;
use ReflectionClass;

/**
 * Pure-unit + source-level tests for the OutboundBluesky envelope.
 *
 * The two-step session-then-publish flow is not exercised against the real
 * network here; the source-level assertions pin the behavior.
 */
class OutboundBlueskyTest extends TestCase
{
    private string $blueskySource;

    protected function setUp(): void
    {
        $path = dirname(__DIR__, 2) . '/src/models/OutboundBluesky.php';
        $this->assertTrue(file_exists($path), "OutboundBluesky.php should exist at: $path");
        $this->blueskySource = file_get_contents($path);
    }

    public function testExtendsBaseEnvelope(): void
    {
        $reflection = new ReflectionClass(OutboundBluesky::class);
        $this->assertTrue($reflection->isSubclassOf(BaseEnvelope::class));
    }

    public function testHasSendMethod(): void
    {
        $reflection = new ReflectionClass(OutboundBluesky::class);
        $this->assertTrue($reflection->hasMethod('send'));
        $this->assertTrue($reflection->getMethod('send')->isPublic());
    }

    public function testDefaultProperties(): void
    {
        $env = new OutboundBluesky();

        $this->assertNull($env->handle);
        $this->assertNull($env->appPassword);
        $this->assertNull($env->label);
        $this->assertSame('', $env->body);
        $this->assertNull($env->language);
        // Link-preview cards are generated by default
        $this->assertTrue($env->linkCard);
    }

    public function testLinkCardPropertyIsABoolDefaultingToTrue(): void
    {
        // The link-card toggle rides in the envelope as a plain bool, default on
        $defaults = (new ReflectionClass(OutboundBluesky::class))->getDefaultProperties();
        $this->assertArrayHasKey('linkCard', $defaults);
        $this->assertTrue($defaults['linkCard']);
    }

    public function testMaxGraphemes(): void
    {
        $this->assertSame(300, OutboundBluesky::MAX_GRAPHEMES);
    }

    public function testHandleResolutionTtlConstant(): void
    {
        // Handle->DID resolution is cached for 24 hours
        $this->assertSame(86400, OutboundBluesky::HANDLE_RESOLUTION_TTL);
    }

    public function testGetMaxGraphemesReturnsTheLimit(): void
    {
        // The public accessor mirrors the MAX_GRAPHEMES constant
        $this->assertSame(300, (new OutboundBluesky())->getMaxGraphemes());
    }

    public function testConstructorHydratesAllProperties(): void
    {
        $env = new OutboundBluesky([
            'handle'      => 'example.bsky.social',
            'appPassword' => 'xxxx-xxxx-xxxx-xxxx',
            'label'       => "example's account",
            'body'        => 'Hello Bluesky.',
            'language'    => 'en',
            'linkCard'    => false,
        ]);

        $this->assertSame('example.bsky.social', $env->handle);
        $this->assertSame('xxxx-xxxx-xxxx-xxxx', $env->appPassword);
        $this->assertSame("example's account", $env->label);
        $this->assertSame('Hello Bluesky.', $env->body);
        $this->assertSame('en', $env->language);
        $this->assertFalse($env->linkCard);
    }

    // ========================================================================= //
    // Source-level guards
    // ========================================================================= //

    public function testSendHitsCreateRecord(): void
    {
        $this->assertStringContainsString('com.atproto.repo.createRecord', $this->blueskySource);
        $this->assertStringContainsString("'app.bsky.feed.post'", $this->blueskySource);
    }

    public function testSendResolvesSessionViaHelper(): void
    {
        $this->assertStringContainsString('BlueskySession::', $this->blueskySource);
    }

    public function testSendChecksGraphemeCountBeforePublishing(): void
    {
        $this->assertStringContainsString('BlueskyFacets::graphemeCount(', $this->blueskySource);
        $this->assertStringContainsString('BlueskyFacets::truncateToGraphemes(', $this->blueskySource);
    }

    public function testSendBuildsFacets(): void
    {
        $this->assertStringContainsString('BlueskyFacets::build(', $this->blueskySource);
    }

    public function testSendIncludesAuthorizationBearerHeader(): void
    {
        $this->assertMatchesRegularExpression(
            "/Bearer\s*\{\\\$session\['accessJwt'\]\}/",
            $this->blueskySource
        );
    }

    public function testSendRetriesOnceOn401(): void
    {
        // After a 401 publish the helper should invalidate the cached session and retry once
        $this->assertStringContainsString('invalidate(', $this->blueskySource);
        $this->assertMatchesRegularExpression('/_lastStatus\s*===\s*401/', $this->blueskySource);
    }

    public function testSendDoesNotLeakAppPasswordToLogs(): void
    {
        // Source should not log the password directly
        $this->assertStringNotContainsString('$this->appPassword}', $this->blueskySource);
    }

    public function testSendUsesEnvParseForPdsUrl(): void
    {
        $this->assertStringContainsString('App::parseEnv($settings->blueskyPdsUrl)', $this->blueskySource);
    }

    public function testSendWarnsOnGraphemeOverflow(): void
    {
        $this->assertStringContainsString('$notification->log->warning(', $this->blueskySource);
    }

    public function testSendDistinguishesAuthFailureFromPostFailure(): void
    {
        $this->assertStringContainsString('[SEND FAILED] Authentication failed', $this->blueskySource);
        $this->assertStringContainsString('[SEND FAILED] {reason}', $this->blueskySource);
    }

    public function testSendFallsBackToDefaultPdsUrl(): void
    {
        // A blank PDS URL setting falls back to the default Bluesky PDS
        $this->assertStringContainsString('?: Settings::DEFAULT_PDS_URL', $this->blueskySource);
    }

    public function testSendBailsWhenCredentialsMissing(): void
    {
        // A recipient missing either the resolved handle or the resolved app password must bail
        $this->assertMatchesRegularExpression(
            '/if\s*\(\s*!\$handle\s*\|\|\s*!\$appPassword\s*\)/',
            $this->blueskySource
        );
    }

    public function testSendResolvesAppPasswordViaEnvParse(): void
    {
        // The app password is resolved through App::parseEnv() so a $ENV_VAR reference works
        $this->assertStringContainsString('App::parseEnv($this->appPassword)', $this->blueskySource);
    }

    public function testSendResolvesHandleViaEnvParse(): void
    {
        // The handle supports $ENV references just like the app password, so it must be parsed at send time
        $this->assertStringContainsString('App::parseEnv($this->handle)', $this->blueskySource);
    }

    // ========================================================================= //
    // Link-preview card (Unit 4)
    // ========================================================================= //

    public function testHasUploadBlobAndAttachLinkCardMethods(): void
    {
        $reflection = new ReflectionClass(OutboundBluesky::class);
        $this->assertTrue($reflection->hasMethod('_uploadBlob'));
        $this->assertTrue($reflection->hasMethod('_attachLinkCard'));
    }

    public function testSendAttachesLinkCardOnlyWhenToggleIsOn(): void
    {
        // The card is attached behind the linkCard flag (and only when no image embed is set)
        $this->assertMatchesRegularExpression(
            '/\$this->linkCard\s*\)\s*\{[\s\S]*?_attachLinkCard\(/',
            $this->blueskySource
        );
    }

    public function testLinkCardIsAttachedAfterBuildRecordAndBeforePublish(): void
    {
        // Ordering: build the record, attach the card, then publish
        $this->assertMatchesRegularExpression(
            '/_buildPostRecord\([\s\S]*?_attachLinkCard\([\s\S]*?_publishRecord\(/',
            $this->blueskySource
        );
    }

    public function testUploadBlobPostsToUploadBlobEndpoint(): void
    {
        $this->assertStringContainsString('com.atproto.repo.uploadBlob', $this->blueskySource);
    }

    public function testUploadBlobSendsImageMimeAndBearerAuth(): void
    {
        // The raw bytes go up with the real image MIME as Content-Type and a Bearer header
        $this->assertMatchesRegularExpression("/'Content-Type'\s*=>\s*\\\$mime/", $this->blueskySource);
        $this->assertMatchesRegularExpression(
            "/Bearer\s*\{\\\$session\['accessJwt'\]\}/",
            $this->blueskySource
        );
    }

    public function testEmbedUsesExternalEmbedType(): void
    {
        // The embed is an app.bsky.embed.external carrying the three required fields
        $this->assertStringContainsString("'app.bsky.embed.external'", $this->blueskySource);
        $this->assertStringContainsString("'external' => \$external", $this->blueskySource);
        $this->assertMatchesRegularExpression("/'uri'\s*=>\s*\\\$meta\['uri'\]/", $this->blueskySource);
        $this->assertMatchesRegularExpression("/'title'\s*=>\s*\\\$meta\['title'\]/", $this->blueskySource);
        $this->assertMatchesRegularExpression("/'description'\s*=>\s*\\\$meta\['description'\]/", $this->blueskySource);
    }

    public function testAttachLinkCardIsBestEffortAndLogsAWarning(): void
    {
        // A failure inside _attachLinkCard() is caught and logged, never rethrown
        $this->assertMatchesRegularExpression(
            '/_attachLinkCard\([\s\S]*?catch\s*\(\s*Throwable/',
            $this->blueskySource
        );
        $this->assertStringContainsString('[LINK PREVIEW SKIPPED] {reason}', $this->blueskySource);
    }
}
